(def-ffi "name")
(def-ffi "name")
(def-ffi "name")
(def-ffi "struct##Set##property")
(def-ffi "cpv")
(def-ffi "cpveql")
(def-ffi "cpvadd")
(def-ffi "cpvneg")
(def-ffi "cpvsub")
(def-ffi "cpvmult")
(def-ffi "cpvdot")
(def-ffi "cpvcross")
(def-ffi "cpvperp")
(def-ffi "cpvrperp")
(def-ffi "cpvproject")
(def-ffi "cpvrotate")
(def-ffi "cpvunrotate")
(def-ffi "cpvlengthsq")
(def-ffi "cpvlerp")
(def-ffi "cpvnormalize")
(def-ffi "cpvnormalize_safe")
(def-ffi "cpvclamp")
(def-ffi "cpvlerpconst")
(def-ffi "cpvdist")
(def-ffi "cpvdistsq")
(def-ffi "cpvnear")
(def-ffi "cpfmax")
(def-ffi "cpfmin")
(def-ffi "cpfabs")
(def-ffi "cpfclamp")
(def-ffi "cpflerp")
(def-ffi "cpflerpconst")
(def-ffi "cpBBNew")
(def-ffi "cpBBNewForCircle")
(def-ffi "cpBBIntersects")
(def-ffi "cpBBContainsBB")
(def-ffi "cpBBContainsVect")
(def-ffi "cpBBMerge")
(def-ffi "cpBBExpand")
(def-ffi "cpBBArea")
(def-ffi "cpBBMergedArea")
(def-ffi "cpBBSegmentQuery")
(def-ffi "cpBBIntersectsSegment")
(def-ffi "cpBodyGetMass")
(def-ffi "cpBodyGetMoment")
(def-ffi "cpBodyGetPos")
(def-ffi "cpBodyGetAngle")
(def-ffi "cpBodyGetRot")
(def-ffi "cpBodyIsSleeping")
(def-ffi "cpBodyIsStatic")
(def-ffi "cpBodyIsRogue")
(def-ffi "cpBodyLocal2World")
(def-ffi "cpBodyWorld2Local")
(def-ffi "cpBodyKineticEnergy")
(def-ffi "cpShapeGetBB")
(def-ffi "cpArbiterGetShapes")
(def-ffi "cpArbiterGetBodies")
(def-ffi "cpArbiterIsFirstContact")
(def-ffi "cpArbiterGetCount")
(def-ffi "cpConstraintGetA")
(def-ffi "cpConstraintGetB")
(def-ffi "cpConstraintGetImpulse")
(def-ffi "cpGearJointGetRatio")
(def-ffi "cpGrooveJointGetGrooveA")
(def-ffi "cpGrooveJointGetGrooveB")
(def-ffi "cpSegmentQueryHitPoint")
(def-ffi "cpSegmentQueryHitDist")
(def-ffi "cpSpatialIndexDestroy")
(def-ffi "cpSpatialIndexCount")
(def-ffi "cpSpatialIndexEach")
(def-ffi "cpSpatialIndexContains")
(def-ffi "cpSpatialIndexInsert")
(def-ffi "cpSpatialIndexRemove")
(def-ffi "cpSpatialIndexReindex")
(def-ffi "cpSpatialIndexReindexObject")
(def-ffi "cpSpatialIndexSegmentQuery")
(def-ffi "cpSpatialIndexQuery")
(def-ffi "cpSpatialIndexReindexQuery")
(def-ffi "cpSpaceGetStaticBody")
(def-ffi "cpSpaceGetCurrentTimeStep")
(def-ffi "cpSpaceIsLocked")
#define MAKE_PROPERTIES_REF(struct, property) \
MAKE_PROPERTIES_REF(cpBody, Vel);
MAKE_PROPERTIES_REF(cpBody, Force);
MAKE_PROPERTIES_REF(cpBody, AngVel);
MAKE_PROPERTIES_REF(cpBody, Torque);
MAKE_PROPERTIES_REF(cpBody, VelLimit);
MAKE_PROPERTIES_REF(cpBody, AngVelLimit);
MAKE_PROPERTIES_REF(cpBody, UserData);
MAKE_PROPERTIES_REF(cpShape, Body);
MAKE_PROPERTIES_REF(cpShape, Sensor);
MAKE_PROPERTIES_REF(cpShape, Elasticity);
MAKE_PROPERTIES_REF(cpShape, Friction);
MAKE_PROPERTIES_REF(cpShape, SurfaceVelocity);
MAKE_PROPERTIES_REF(cpShape, UserData);
MAKE_PROPERTIES_REF(cpShape, CollisionType);
MAKE_PROPERTIES_REF(cpShape, Group);
MAKE_PROPERTIES_REF(cpShape, Layers);
MAKE_PROPERTIES_REF(cpConstraint, MaxForce);
MAKE_PROPERTIES_REF(cpConstraint, ErrorBias);
MAKE_PROPERTIES_REF(cpConstraint, MaxBias);
MAKE_PROPERTIES_REF(cpConstraint, UserData);
MAKE_PROPERTIES_REF(cpDampedRotarySpring, RestAngle);
MAKE_PROPERTIES_REF(cpDampedRotarySpring, Stiffness);
MAKE_PROPERTIES_REF(cpDampedRotarySpring, Damping);
//MAKE_PROPERTIES_REF(cpDampedRotarySpring, SpringTorqueFunc);
MAKE_PROPERTIES_REF(cpDampedSpring, Anchr1);
MAKE_PROPERTIES_REF(cpDampedSpring, Anchr2);
MAKE_PROPERTIES_REF(cpDampedSpring, RestLength);
MAKE_PROPERTIES_REF(cpDampedSpring, Stiffness);
MAKE_PROPERTIES_REF(cpDampedSpring, Damping);
//MAKE_PROPERTIES_REF(cpDampedSpring, SpringForceFunc);
MAKE_PROPERTIES_REF(cpGearJoint, Phase);
MAKE_PROPERTIES_REF(cpGrooveJoint, Anchr2);
MAKE_PROPERTIES_REF(cpPinJoint, Anchr1);
MAKE_PROPERTIES_REF(cpPinJoint, Anchr2);
MAKE_PROPERTIES_REF(cpPinJoint, Dist);
MAKE_PROPERTIES_REF(cpPivotJoint, Anchr1);
MAKE_PROPERTIES_REF(cpPivotJoint, Anchr2);
MAKE_PROPERTIES_REF(cpRatchetJoint, Angle);
MAKE_PROPERTIES_REF(cpRatchetJoint, Phase);
MAKE_PROPERTIES_REF(cpRatchetJoint, Ratchet);
MAKE_PROPERTIES_REF(cpRotaryLimitJoint, Min);
MAKE_PROPERTIES_REF(cpRotaryLimitJoint, Max);
MAKE_PROPERTIES_REF(cpSimpleMotor, Rate);
MAKE_PROPERTIES_REF(cpSlideJoint, Anchr1);
MAKE_PROPERTIES_REF(cpSlideJoint, Anchr2);
MAKE_PROPERTIES_REF(cpSlideJoint, Min);
MAKE_PROPERTIES_REF(cpSlideJoint, Max);
MAKE_PROPERTIES_REF(cpSpace, Iterations);
MAKE_PROPERTIES_REF(cpSpace, Gravity);
MAKE_PROPERTIES_REF(cpSpace, Damping);
MAKE_PROPERTIES_REF(cpSpace, IdleSpeedThreshold);
MAKE_PROPERTIES_REF(cpSpace, SleepTimeThreshold);
MAKE_PROPERTIES_REF(cpSpace, CollisionSlop);
MAKE_PROPERTIES_REF(cpSpace, CollisionBias);
MAKE_PROPERTIES_REF(cpSpace, CollisionPersistence);
MAKE_PROPERTIES_REF(cpSpace, EnableContactGraph);
MAKE_PROPERTIES_REF(cpSpace, UserData);
(def-ffi "cpv")
(def-ffi "cpveql")
(def-ffi "cpvadd")
(def-ffi "cpvneg")
(def-ffi "cpvsub")
(def-ffi "cpvmult")
(def-ffi "cpvdot")
(def-ffi "cpvcross")
(def-ffi "cpvperp")
(def-ffi "cpvrperp")
(def-ffi "cpvproject")
(def-ffi "cpvrotate")
(def-ffi "cpvunrotate")
(def-ffi "cpvlengthsq")
(def-ffi "cpvlerp")
(def-ffi "cpvnormalize")
(def-ffi "cpvnormalize_safe")
(def-ffi "cpvclamp")
(def-ffi "cpvlerpconst")
(def-ffi "cpvdist")
(def-ffi "cpvdistsq")
(def-ffi "cpvnear")
(def-ffi "cpfmax")
(def-ffi "cpfmin")
(def-ffi "cpfabs")
(def-ffi "cpfclamp")
(def-ffi "cpflerp")
(def-ffi "cpflerpconst")
(def-ffi "cpBBNew")
(def-ffi "cpBBNewForCircle")
(def-ffi "cpBBIntersects")
(def-ffi "cpBBContainsBB")
(def-ffi "cpBBContainsVect")
(def-ffi "cpBBMerge")
(def-ffi "cpBBExpand")
(def-ffi "cpBBArea")
(def-ffi "cpBBMergedArea")
(def-ffi "cpBBSegmentQuery")
(def-ffi "cpBBIntersectsSegment")
(def-ffi "cpBodyGetMass")
(def-ffi "cpBodyGetMoment")
(def-ffi "cpBodyGetPos")
(def-ffi "cpBodyGetAngle")
(def-ffi "cpBodyGetRot")
(def-ffi "cpBodyIsSleeping")
(def-ffi "cpBodyIsStatic")
(def-ffi "cpBodyIsRogue")
(def-ffi "cpBodyLocal2World")
(def-ffi "cpBodyWorld2Local")
(def-ffi "cpBodyKineticEnergy")
(def-ffi "cpShapeGetBB")
(def-ffi "cpArbiterGetShapes")
(def-ffi "cpArbiterGetBodies")
(def-ffi "cpArbiterIsFirstContact")
(def-ffi "cpArbiterGetCount")
(def-ffi "cpConstraintGetA")
(def-ffi "cpConstraintGetB")
(def-ffi "cpConstraintGetImpulse")
(def-ffi "cpGearJointGetRatio")
(def-ffi "cpGrooveJointGetGrooveA")
(def-ffi "cpGrooveJointGetGrooveB")
(def-ffi "cpSegmentQueryHitPoint")
(def-ffi "cpSegmentQueryHitDist")
(def-ffi "cpSpatialIndexDestroy")
(def-ffi "cpSpatialIndexCount")
(def-ffi "cpSpatialIndexEach")
(def-ffi "cpSpatialIndexContains")
(def-ffi "cpSpatialIndexInsert")
(def-ffi "cpSpatialIndexRemove")
(def-ffi "cpSpatialIndexReindex")
(def-ffi "cpSpatialIndexReindexObject")
(def-ffi "cpSpatialIndexSegmentQuery")
(def-ffi "cpSpatialIndexQuery")
(def-ffi "cpSpatialIndexReindexQuery")
(def-ffi "cpSpaceGetStaticBody")
(def-ffi "cpSpaceGetCurrentTimeStep")
(def-ffi "cpSpaceIsLocked")
MAKE_PROPERTIES_REF(cpBody, Vel);
MAKE_PROPERTIES_REF(cpBody, Force);
MAKE_PROPERTIES_REF(cpBody, AngVel);
MAKE_PROPERTIES_REF(cpBody, Torque);
MAKE_PROPERTIES_REF(cpBody, VelLimit);
MAKE_PROPERTIES_REF(cpBody, AngVelLimit);
MAKE_PROPERTIES_REF(cpBody, UserData);
MAKE_PROPERTIES_REF(cpShape, Body);
MAKE_PROPERTIES_REF(cpShape, Sensor);
MAKE_PROPERTIES_REF(cpShape, Elasticity);
MAKE_PROPERTIES_REF(cpShape, Friction);
MAKE_PROPERTIES_REF(cpShape, SurfaceVelocity);
MAKE_PROPERTIES_REF(cpShape, UserData);
MAKE_PROPERTIES_REF(cpShape, CollisionType);
MAKE_PROPERTIES_REF(cpShape, Group);
MAKE_PROPERTIES_REF(cpShape, Layers);
MAKE_PROPERTIES_REF(cpConstraint, MaxForce);
MAKE_PROPERTIES_REF(cpConstraint, ErrorBias);
MAKE_PROPERTIES_REF(cpConstraint, MaxBias);
MAKE_PROPERTIES_REF(cpConstraint, UserData);
MAKE_PROPERTIES_REF(cpDampedRotarySpring, RestAngle);
MAKE_PROPERTIES_REF(cpDampedRotarySpring, Stiffness);
MAKE_PROPERTIES_REF(cpDampedRotarySpring, Damping);
MAKE_PROPERTIES_REF(cpDampedSpring, Anchr1);
MAKE_PROPERTIES_REF(cpDampedSpring, Anchr2);
MAKE_PROPERTIES_REF(cpDampedSpring, RestLength);
MAKE_PROPERTIES_REF(cpDampedSpring, Stiffness);
MAKE_PROPERTIES_REF(cpDampedSpring, Damping);
MAKE_PROPERTIES_REF(cpGearJoint, Phase);
MAKE_PROPERTIES_REF(cpGrooveJoint, Anchr2);
MAKE_PROPERTIES_REF(cpPinJoint, Anchr1);
MAKE_PROPERTIES_REF(cpPinJoint, Anchr2);
MAKE_PROPERTIES_REF(cpPinJoint, Dist);
MAKE_PROPERTIES_REF(cpPivotJoint, Anchr1);
MAKE_PROPERTIES_REF(cpPivotJoint, Anchr2);
MAKE_PROPERTIES_REF(cpRatchetJoint, Angle);
MAKE_PROPERTIES_REF(cpRatchetJoint, Phase);
MAKE_PROPERTIES_REF(cpRatchetJoint, Ratchet);
MAKE_PROPERTIES_REF(cpRotaryLimitJoint, Min);
MAKE_PROPERTIES_REF(cpRotaryLimitJoint, Max);
MAKE_PROPERTIES_REF(cpSimpleMotor, Rate);
MAKE_PROPERTIES_REF(cpSlideJoint, Anchr1);
MAKE_PROPERTIES_REF(cpSlideJoint, Anchr2);
MAKE_PROPERTIES_REF(cpSlideJoint, Min);
MAKE_PROPERTIES_REF(cpSlideJoint, Max);
MAKE_PROPERTIES_REF(cpSpace, Iterations);
MAKE_PROPERTIES_REF(cpSpace, Gravity);
MAKE_PROPERTIES_REF(cpSpace, Damping);
MAKE_PROPERTIES_REF(cpSpace, IdleSpeedThreshold);
MAKE_PROPERTIES_REF(cpSpace, SleepTimeThreshold);
MAKE_PROPERTIES_REF(cpSpace, CollisionSlop);
MAKE_PROPERTIES_REF(cpSpace, CollisionBias);
MAKE_PROPERTIES_REF(cpSpace, CollisionPersistence);
MAKE_PROPERTIES_REF(cpSpace, EnableContactGraph);
MAKE_PROPERTIES_REF(cpSpace, UserData);
